# Generated by Django 4.0.1 on 2022-03-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableprofile',
            name='url_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
